import { Signal } from "./qt";

export interface Options {
    readonly focusPolicy: number;
    readonly xwaylandCrashPolicy: number;
    readonly xwaylandMaxCrashCount: number;
    readonly nextFocusPrefersMouse: boolean;
    readonly clickRaise: boolean;
    readonly autoRaise: boolean;
    readonly autoRaiseInterval: number;
    readonly delayFocusInterval: number;
    readonly shadeHover: boolean;
    readonly shadeHoverInterval: number;
    readonly separateScreenFocus: boolean;
    readonly activeMouseScreen: boolean;
    readonly placement: number;
    readonly activationDesktopPolicy: number;
    readonly focusPolicyIsReasonable: boolean;
    readonly borderSnapZone: number;
    readonly windowSnapZone: number;
    readonly centerSnapZone: number;
    readonly snapOnlyWhenOverlapping: boolean;
    readonly rollOverDesktops: boolean;
    readonly focusStealingPreventionLevel: number;
    readonly operationTitlebarDblClick: number;
    readonly operationMaxButtonLeftClick: number;
    readonly operationMaxButtonMiddleClick: number;
    readonly operationMaxButtonRightClick: number;
    readonly commandActiveTitlebar1: number;
    readonly commandActiveTitlebar2: number;
    readonly commandActiveTitlebar3: number;
    readonly commandInactiveTitlebar1: number;
    readonly commandInactiveTitlebar2: number;
    readonly commandInactiveTitlebar3: number;
    readonly commandWindow1: number;
    readonly commandWindow2: number;
    readonly commandWindow3: number;
    readonly commandWindowWheel: number;
    readonly commandAll1: number;
    readonly commandAll2: number;
    readonly commandAll3: number;
    readonly keyCmdAllModKey: number;
    readonly condensedTitle: boolean;
    readonly electricBorderMaximize: boolean;
    readonly electricBorderTiling: boolean;
    readonly electricBorderCornerRatio: number;
    readonly borderlessMaximizedWindows: boolean;
    readonly killPingTimeout: number;
    readonly hideUtilityWindowsForInactive: boolean;
    readonly compositingMode: number;
    readonly useCompositing: boolean;
    readonly hiddenPreviews: number;
    readonly glSmoothScale: number;
    readonly glStrictBinding: boolean;
    readonly glStrictBindingFollowsDriver: boolean;
    readonly glPreferBufferSwap: number;
    readonly glPlatformInterface: number;
    readonly windowsBlockCompositing: boolean;
    readonly allowTearing: boolean;

    readonly configChanged: Signal<() => void>;
    readonly focusPolicyChanged: Signal<() => void>;
    readonly focusPolicyIsResonableChanged: Signal<() => void>;
    readonly xwaylandCrashPolicyChanged: Signal<() => void>;
    readonly xwaylandMaxCrashCountChanged: Signal<() => void>;
    readonly xwaylandEavesdropsChanged: Signal<() => void>;
    readonly nextFocusPrefersMouseChanged: Signal<() => void>;
    readonly clickRaiseChanged: Signal<() => void>;
    readonly autoRaiseChanged: Signal<() => void>;
    readonly autoRaiseIntervalChanged: Signal<() => void>;
    readonly delayFocusIntervalChanged: Signal<() => void>;
    readonly shadeHoverChanged: Signal<() => void>;
    readonly shadeHoverIntervalChanged: Signal<() => void>;
    readonly separateScreenFocusChanged: Signal<() => void>;
    readonly activeMouseScreenChanged: Signal<() => void>;
    readonly placementChanged: Signal<() => void>;
    readonly activationDesktopPolicyChanged: Signal<() => void>;
    readonly borderSnapZoneChanged: Signal<() => void>;
    readonly windowSnapZoneChanged: Signal<() => void>;
    readonly centerSnapZoneChanged: Signal<() => void>;
    readonly snapOnlyWhenOverlappingChanged: Signal<() => void>;
    readonly rollOverDesktopsChanged: Signal<() => void>;
    readonly focusStealingPreventionLevelChanged: Signal<() => void>;
    readonly operationTitlebarDblClickChanged: Signal<() => void>;
    readonly operationMaxButtonLeftClickChanged: Signal<() => void>;
    readonly operationMaxButtonRightClickChanged: Signal<() => void>;
    readonly operationMaxButtonMiddleClickChanged: Signal<() => void>;
    readonly commandActiveTitlebar1Changed: Signal<() => void>;
    readonly commandActiveTitlebar2Changed: Signal<() => void>;
    readonly commandActiveTitlebar3Changed: Signal<() => void>;
    readonly commandInactiveTitlebar1Changed: Signal<() => void>;
    readonly commandInactiveTitlebar2Changed: Signal<() => void>;
    readonly commandInactiveTitlebar3Changed: Signal<() => void>;
    readonly commandWindow1Changed: Signal<() => void>;
    readonly commandWindow2Changed: Signal<() => void>;
    readonly commandWindow3Changed: Signal<() => void>;
    readonly commandWindowWheelChanged: Signal<() => void>;
    readonly commandAll1Changed: Signal<() => void>;
    readonly commandAll2Changed: Signal<() => void>;
    readonly commandAll3Changed: Signal<() => void>;
    readonly keyCmdAllModKeyChanged: Signal<() => void>;
    readonly condensedTitleChanged: Signal<() => void>;
    readonly electricBorderMaximizeChanged: Signal<() => void>;
    readonly electricBorderTilingChanged: Signal<() => void>;
    readonly electricBorderCornerRatioChanged: Signal<() => void>;
    readonly borderlessMaximizedWindowsChanged: Signal<() => void>;
    readonly killPingTimeoutChanged: Signal<() => void>;
    readonly hideUtilityWindowsForInactiveChanged: Signal<() => void>;
    readonly compositingModeChanged: Signal<() => void>;
    readonly useCompositingChanged: Signal<() => void>;
    readonly hiddenPreviewsChanged: Signal<() => void>;
    readonly glSmoothScaleChanged: Signal<() => void>;
    readonly glStrictBindingChanged: Signal<() => void>;
    readonly glStrictBindingFollowsDriverChanged: Signal<() => void>;
    readonly glPreferBufferSwapChanged: Signal<() => void>;
    readonly glPlatformInterfaceChanged: Signal<() => void>;
    readonly windowsBlockCompositingChanged: Signal<() => void>;
    readonly animationSpeedChanged: Signal<() => void>;
    readonly allowTearingChanged: Signal<() => void>;
}