import { QRect, QPoint, QSize, QUuid, QIcon, Signal } from "./qt";

import { Output } from "./output";
import { Tile } from "./tile";
import { VirtualDesktop } from "./virtualdesktop";
import { MaximizeMode } from "./enums";
import { Activity } from "./baseWorkspace";

export interface Window {
    readonly bufferGeometry: QRect;
    readonly clientGeometry: QRect;
    readonly pos: QPoint;
    readonly size: QSize;
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
    readonly output: Output;
    readonly rect: QRect;
    readonly resourceName: string;
    readonly resourceClass: string;
    readonly windowRole: string;
    readonly desktopWindow: boolean;
    readonly dock: boolean;
    readonly toolbar: boolean;
    readonly menu: boolean;
    readonly normalWindow: boolean;
    readonly dialog: boolean;
    readonly splash: boolean;
    readonly utility: boolean;
    readonly dropdownMenu: boolean;
    readonly popupMenu: boolean;
    readonly tooltip: boolean;
    readonly notification: boolean;
    readonly criticalNotification: boolean;
    readonly appletPopup: boolean;
    readonly onScreenDisplay: boolean;
    readonly comboBox: boolean;
    readonly dndIcon: boolean;
    readonly windowType: number;
    readonly managed: boolean;
    readonly deleted: boolean;
    readonly popupWindow: boolean;
    readonly outline: boolean;
    readonly internalId: QUuid;
    readonly pid: number;
    readonly stackingOrder: number;
    readonly fullScreenable: boolean;
    readonly active: boolean;
    readonly closeable: boolean;
    readonly icon: QIcon;
    readonly shadeable: boolean;
    readonly minimizable: boolean;
    readonly iconGeometry: QSize;
    readonly specialWindow: boolean;
    readonly caption: string;
    readonly minSize: QSize;
    readonly maxSize: QSize;
    readonly wantsInput: boolean;
    readonly transient: boolean;
    readonly transientFor: Window | null;
    readonly modal: boolean;
    readonly move: boolean;
    readonly resize: boolean;
    readonly decorationHasAlpha: boolean;
    readonly providesContextHelp: boolean;
    readonly maximizable: boolean;
    readonly moveable: boolean;
    readonly moveableAcrossScreens: boolean;
    readonly resizeable: boolean;
    readonly desktopFileName: string;
    readonly hasApplicationMenu: boolean;
    readonly applicationMenuActive: boolean;
    readonly unresponsive: boolean;
    readonly colorScheme: string;
    readonly layer: number;
    readonly hidden: boolean;
    readonly inputMethod: boolean;

    opacity: number;
    skipsCloseAnimation: boolean;
    fullScreen: boolean;
    desktops: VirtualDesktop[];
    onAllDesktops: boolean;
    activities: Activity[];
    skipTaskbar: boolean;
    skipPager: boolean;
    skipSwitcher: boolean;
    keepAbove: boolean;
    keepBelow: boolean;
    shade: boolean;
    minimized: boolean;
    demandsAttention: boolean;
    frameGeometry: QRect;
    noBorder: boolean;
    /**
     * @deprecated Use tile.manage() instead!
     */
    tile: Tile | null;
 
    closeWindow(): void;
    //setReadyForPainting(): void;
    setMaximize(vertical: boolean, horizontal: boolean): void;

    readonly stackingOrderChanged: Signal<() => void>;
    readonly shadeChanged: Signal<() => void>;
    readonly opacityChanged: Signal<(window: Window, oldOpacity: number) => void>;
    readonly damaged: Signal<(window: Window) => void>;
    readonly inputTransformationChanged: Signal<() => void>;
    readonly closed: Signal<() => void>;
    readonly windowShown: Signal<(window: Window) => void>;
    readonly windowHidden: Signal<(window: Window) => void>;
    readonly outputChanged: Signal<() => void>;
    readonly skipCloseAnimationChanged: Signal<() => void>;
    readonly windowRoleChanged: Signal<() => void>;
    readonly windowClassChanged: Signal<() => void>;
    readonly surfaceChanged: Signal<() => void>;
    readonly shadowChanged: Signal<() => void>;
    readonly bufferGeometryChanged: Signal<(oldGeometry: QRect) => void>;
    readonly frameGeometryChanged: Signal<(oldGeometry: QRect) => void>;
    readonly clientGeometryChanged: Signal<(oldGeometry: QRect) => void>;
    readonly frameGeometryAboutToChange: Signal<() => void>;
    readonly visibleGeometryChanged: Signal<() => void>;
    readonly tileChanged: Signal<(tile: Tile) => void>;
    readonly fullScreenChanged: Signal<() => void>;
    readonly skipTaskbarChanged: Signal<() => void>;
    readonly skipPagerChanged: Signal<() => void>;
    readonly skipSwitcherChanged: Signal<() => void>;
    readonly iconChanged: Signal<() => void>;
    readonly activeChanged: Signal<() => void>;
    readonly keepAboveChanged: Signal<(keepAbove: boolean) => void>;
    readonly keepBelowChanged: Signal<(keepBelow: boolean) => void>;
    readonly demandsAttentionChanged: Signal<() => void>;
    readonly desktopsChanged: Signal<() => void>;
    readonly activitiesChanged: Signal<() => void>;
    readonly minimizedChanged: Signal<() => void>;
    readonly paletteChanged: Signal<() => void>;
    readonly colorSchemeChanged: Signal<() => void>;
    readonly captionChanged: Signal<() => void>;
    readonly captionNormalChanged: Signal<() => void>;
    readonly maximizedAboutToChange: Signal<(mode: MaximizeMode) => void>;
    readonly maximizedChanged: Signal<() => void>;
    readonly transientChanged: Signal<() => void>;
    readonly modalChanged: Signal<() => void>;
    readonly quickTileModeChanged: Signal<() => void>;
    readonly moveResizedChanged: Signal<() => void>;
    readonly moveResizeCursorChanged: Signal<() => void>;
    readonly interactiveMoveResizeStarted: Signal<() => void>;
    readonly interactiveMoveResizeStepped: Signal<(oldGeometry: QRect) => void>;
    readonly interactiveMoveResizeFinished: Signal<() => void>;
    readonly closeableChanged: Signal<() => void>;
    readonly minimizeableChanged: Signal<(minimizeable: boolean) => void>;
    readonly shadeableChanged: Signal<(shadeable: boolean) => void>;
    readonly maximizeableChanged: Signal<(maximizeable: boolean) => void>;
    readonly desktopFileNameChanged: Signal<() => void>;
    readonly applicationMenuChanged: Signal<() => void>;
    readonly hasApplicationMenuChanged: Signal<(hasApplicationMenu: boolean) => void>;
    readonly applicationMenuActiveChanged: Signal<(active: boolean) => void>;
    readonly unresponsiveChanged: Signal<(unresponsive: boolean) => void>;
    readonly decorationChanged: Signal<() => void>;
    readonly hiddenChanged: Signal<() => void>;
    readonly hiddenByShowDesktopChanged: Signal<() => void>;
    readonly lockScreenOverlayChanged: Signal<() => void>;
    readonly readyForPaintingChanged: Signal<() => void>;
}